services:
  # Banco de Dados MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456' 
      MYSQL_DATABASE: 'programacoes_filmes' 
    volumes:
      - db_data:/var/lib/mysql # Persistência dos dados
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql # Script de inicialização
    ports:
      - "3307:3306"

  # Serviço da Aplicação Streamlit
  app:
    build: . # Constrói a imagem a partir do Dockerfile 
    container_name: streamlit_app
    restart: always
    ports:
      - "8501:8501"
    environment:
      # Variáveis de ambiente 
      DB_HOST: 'db' # 'db' é o nome do serviço do banco de dados
      DB_USER: 'root'
      DB_PASSWORD: '123456' 
      DB_NAME: 'programacoes_filmes' 
    depends_on:
      - db # 'db' inicia antes do serviço 'app'
    develop:
      watch:
        # Se o requirements.txt mudar, reconstrói a imagem
        - action: rebuild
          path: ./requirements.txt
        # Para qualquer outra mudança nos arquivos .py, sincroniza
        - action: sync
          path: .
          target: /app
          ignore:
            - venv/
            - .git/
            - .vscode/
    
  db-admin:
    image: adminer
    container_name: db_admin_ui
    restart: always
    ports:
      - "8081:8080" # Acessaremos o Adminer pela porta 8081 do nosso PC
    depends_on:
      - db

volumes:
  db_data: # Define o volume nomeado para persistência